### ISSUE TITLE
Support for IOS

### ISSUE THREAD

**Issue by rohitsangwan01** [Alystrasz/grant_and_activate#3]
Hey , i was looking for something like this , am just wondering if i can turn on Bluetooth and Location on IOS too

**Comment by Alystrasz** [comment]
Hello @rohitsangwan01, you should be able to turn on Location and Bluetooth services on iOS with this package (latest PR #2 added missing iOS Bluetooth support) :)

**Comment by rohitsangwan01** [comment]
great , is this plugin ready to use in production, or u woking on few more (breakin) changes??

**Comment by Alystrasz** [comment]
I may add some features in the future or fix some potential bugs, but the API should not change.
You can try version `0.0.6`: https://pub.dev/packages/grant_and_activate

**Comment by rohitsangwan01** [comment]
> 

okk thanks

**Comment by rohitsangwan01** [comment]
@Alystrasz  , can you please add one more method to just check if Provided Features are on or Off ,instead of turning them on directly , or maybe a parameter in that method , like ,   await 
```dart
Result result = checkPermissionsAndActivateServices([features] , autoTurnon : false);
```

Something like this will work

```dart
Future<Result> checkPermissionsAndActivateServices(List<Feature> features,
    {bool AutoTurnOn = true}) async {
  if (features.length == 0) throw ArgumentError('No input features provided.');

  Map<Feature, bool> results = Map();
  for (var feature in features) {
    bool result = AutoTurnOn
        ? await checkPermissions(feature) && await activateService(feature)
        : await checkPermissions(feature);
    results.putIfAbsent(feature, () => result);
  }

  return Result(results, allOk: !results.values.contains(false));
}
```

**Comment by Alystrasz** [comment]
I feel like your modification diverts from this package objective.
Moreover, you can already check features state by calling the `checkPermissions` method.

**Comment by rohitsangwan01** [comment]
yeah ```checkPermissions``` will do the job , Thanks
